# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-16 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0002_subscriber_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
