# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-17 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0003_subscriber_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField()),
                ('opened', models.BooleanField(default=False)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_app.Subscriber')),
            ],
        ),
    ]
