# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2022-11-17 07:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0006_auto_20221117_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letterinfo',
            name='sent',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 17, 7, 27, 14, 496356, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='letterinfo',
            name='subscriber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_app.Subscriber'),
        ),
    ]
